$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: mlflow-deployment
endpoint_name: price-prediction-ep
model: azureml:Taxi-Data:latest
instance_type: Standard_DS3_v2
instance_count: 1
